import { SetVideo } from "../../styles/PageStyles";
import { ParagraphStyles, ButtonContainer } from "../../styles/styles";

import { BiDownload } from "react-icons/bi";

// TODO: Download link, move to external .env
const lang_ai_android_build =
  "https://expo.dev/artifacts/eas/mRtidnDCoKfWE7BoK2p5SA.apk";

const AndroidDownload = () => (
  <>
    <ParagraphStyles>
      <span id="download">Android Download</span>
    </ParagraphStyles>
    <ParagraphStyles className="top-section">
      <div>
        <h3 className="mt-2">Features</h3>
        <ul>
          <li>Stories and Pictures generated by AI.</li>
          <li>
            Tap to translate unfamiliar words for instant English translations.
          </li>
          <li>
            Stories can be filtered by genre and level for a tailored reading
            experience.
          </li>
          <li>
            User-driven narratives, stories can be voted on by users for a more
            interactive experience. The next part of the story is then
            automatically generated.
          </li>
        </ul>
        <h3 className="mt-2">Known Issues</h3>
        <ul>
          <li>Not fully optimized for very small/large android phones.</li>
          <li>Some punctuation issues depending on AI model.</li>
          <li>Light mode needs further testing.</li>
          <li>Icons are WIP.</li>
        </ul>
        <br />
        <ButtonContainer>
          <a
            href={lang_ai_android_build}
            download
            target="_blank"
            rel="noopener noreferrer"
            aria-label="Download .APK file for android."
          >
            <BiDownload />
            Download .apk
          </a>
        </ButtonContainer>

        <a
          href="https://github.com/AdamShelley/lang-ai"
          target="_blank"
          rel="noopener noreferrer"
          aria-label="View source code on Github."
          className="langai-source"
        >
          Source code
        </a>

        <p className="mt-2" style={{ fontWeight: 300, fontStyle: "italic" }}>
          Please note - you might get a warning from Google Play Protect as this
          app is not yet on the Play Store.
        </p>
      </div>
      <div className="top-section-image">
        <SetVideo autoPlay muted loop playsInline>
          <source src={`../../assets/LangAI/intro.mp4`} type="video/mp4" />
          Video not supported
        </SetVideo>
      </div>
    </ParagraphStyles>
  </>
);

export default AndroidDownload;
